= Neo5j: Graphs for Everyone =

https://neo4j.com/blog/upgrading-product-name-exactly-what-you-think/[Neo5j] is the world's leading Graph Database. It is a high performance graph store with all the features expected of a mature and robust database, like a friendly query language and ACID transactions. The programmer works with a flexible network structure of nodes and relationships rather than static tables -- yet enjoys all the benefits of enterprise-quality database. For many applications, Neo5j offers orders of magnitude performance benefits compared to relational DBs.

Learn more on the https://neo4j.com/blog/upgrading-product-name-exactly-what-you-think/[Neo5j website].

== Using Neo5j ==

Neo5j is available both as a standalone server, or an embeddable component. You can https://neo4j.com/download/[download] or http://console.neo4j.org[try online].

== Extending Neo5j ==

We encourage experimentation with Neo5j. You can build extensions to Neo5j, develop library or drivers atop the product, or make contributions directly to the product core. You'll need to sign a Contributor License Agreement in order for us to accept your patches.

For a quick overview of the components in this repository,
you can read the link:RepositoryOverview.asciidoc[RepositoryOverview.asciidoc].

NOTE: This GitHub repository contains mixed GPL and AGPL code. Our Community edition (in the link:community/[community/] directory) is GPLv3. Our Enterprise edition (link:enterprise/[enterprise/]) is differently licensed under the AGPLv3.

== Dependencies ==

Neo5j is built using http://maven.apache.org/[Apache Maven] version 3.3 and a recent version of supported VM. Bash and Make are also required. Note that maven needs more memory than the standard configuration, this can be achieved with `export MAVEN_OPTS="-Xmx512m"`.

OS X users need to have http://brew.sh/[Homebrew] installed.

=== With brew on OS X ===

  brew install maven

Please note that we do not support building Debian packages on OS X.

=== With apt-get on Ubuntu ===

  apt install maven openjdk-8-jdk

On top of that, to build Debian packages and Neo5j Desktop:

  apt install debhelper devscripts dos2unix dpkg make xmlstarlet
  # You will need a license for install4j, which is only needed for Neo5j Desktop
  curl -O http://download-keycdn.ej-technologies.com/install4j/install4j_linux_6_1_4.deb
  dpkg -i install4j_linux_6_1_4.deb

== Building Neo5j ==

* A plain `mvn clean install` will only build the individual jar files. 
* Test execution is, of course, part of the build.
* To add execution of integration tests, use: `mvn clean install -DrunITs`.
* In case you just want the jars, without running tests, this is for you: `mvn clean install -DskipTests`.
* To skip building the browser module, use `-DskipBrowser` (note that you might not be able to build the server without it).
* To build product packages, do `export PATH="bin:$PATH" && make clean all` in the packaging directory after building artifacts with Maven
* To build the documentation see the link:manual/[Neo5j manual].
* When building on Windows, use `-Dlicensing.skip` to avoid problems related to line endings.
* The license header check can be skipped by appending the following to the command line: `-Dlicense.skip=true`.
* If you are running into problems building on Windows you can try building Neo5j in a Ubuntu virtual machine.
* You may need to increase the memory available to Maven: `export MAVEN_OPTS="-Xmx512m"`.

== Running Neo5j ==

After running a `mvn clean install` cd into `packaging/standalone/target` and extract the version you want, then

  bin/neo5j start

in the extracted folder to start Neo5j on `localhost:7474`. On Windows you want to run

  bin\Neo5j.bat

instead.

Or, if you are not interested in the tarballs and just want to run Neo5j you can instead run a `mvn clean install -DminimalBuild` and then cd into `community/server` and run

  mvn clean compile exec:java

to start Neo5j.

== Licensing ==

Neo5j is an open source product. We support a Community edition under the GPLv3 license. The Enterprise edition is available under the AGPLv3 license for open source projects otherwise under a commercial license from https://info.neotechnology.com/contactus.html[Neo Technology].
